# Bab 3: Indexing & Selection (Pengindeksan & Pemilihan Data) - Cara Memotong Data ML

## A. Definisi & Fungsi Utama
Di dalam workflow AI/ML, kemampuan memilih baris dan kolom secara spesifik sangatlah krusial. Tahapan ini digunakan untuk:
1. Memisahkan dataset menjadi variabel **Fitur ($X$)** dan **Target ($y$)**.
2. Membuang data pencilan (**Outliers**) yang terdeteksi saat tahapan *Data Inspection*.
3. Memisahkan kolom berdasarkan tipe datanya (Numerik vs Kategorikal) untuk proses *Feature Engineering*.

---

## B. 3 Cara Utama Pemilihan Data (Slicing & Selecting)

### 1. Metode Dasar (Bracket Notation `[]`)
Cara paling ringkas untuk memilih kolom tertentu.
* `df['Nama_Kolom']` $\rightarrow$ Mengambil 1 kolom. Menghasilkan objek **Series**.
* `df[['Kolom_A', 'Kolom_B']]` $\rightarrow$ Mengambil beberapa kolom sekaligus. Menghasilkan objek **DataFrame**.

```python
import numpy as np
import pandas as pd

# Dataset Contoh
data = {
    "Nama": ["Ali", "Budi", "Cici", "Dedi"],
    "Usia": [23, 45, 31, 35],
    "Tekanan_Darah": [120, 140, 118, 130]
}
df = pd.DataFrame(data, index=["P1", "P2", "P3", "P4"])

# Mengambil satu kolom (Series)
usia = df['Usia']

# Mengambil dua kolom (DataFrame - Wajib kurung siku ganda)
fitur_medis = df[['Usia', 'Tekanan_Darah']]
```

### 2. Seleksi Berdasarkan Label (`df.loc[]`)
Memilih baris dan kolom berdasarkan Label/Nama Teks nya.
📌 Aturan Penulisan: `df.loc[label_baris, label_kolom]`

```python
# Mengambil baris 'P2' sampai 'P3' untuk kolom 'Nama' dan 'Tekanan_Darah'
# Catatan: Slicing label pada .loc bersifat inklusif (Batas akhir 'P3' ikut terbawa)
df_hasil_loc = df.loc["P2":"P3", ["Nama", "Tekanan_Darah"]]
```

### 3. Seleksi Berdasarkan Posisi Angka (`df.iloc[]`)
Memilih baris dan kolom berdasarkan posisi angka index-nya ($0$, $1$, $2$, ...), persis seperti slicing pada NumPy array atau List Python bawaan.
📌 Aturan Penulisan: `df.iloc[posisi_baris, posisi_kolom]`

```python
# Mengambil baris indeks 1 sampai sebelum 3, dan kolom indeks 0 sampai sebelum 2
# Catatan: Slicing .iloc bersifat eksklusif (Batas akhir angka 3 dan 2 tidak ikut terbawa)
df_hasil_iloc = df.iloc[1:3, 0:2]

# Poin ML (Memotong Fitur X): Ambil semua baris, dan ambil semua kolom KECUALI kolom terakhir
X = df.iloc[:, :-1]
```

---

## C. Penyaringan Data Berdasarkan Kondisi (Boolean Indexing)
Teknik menyaring baris fisik DataFrame berdasarkan syarat atau logika matematika tertentu. Sangat berguna untuk menyarin *outliners*.

```python
# 1. Filter dasar: Mencari pasien dengan Usia di atas 30 tahun
df_tua = df[df["Usia"] > 30]

# 2. Filter Multi-Kondisi: Menggunakan operator logika & (AND) atau | (OR)
# Wajib hukumnya menggunakan tanda kurung () di setiap kondisi!
df_khusus = df[(df["Usia"] > 30) & (df["Tekanan_Darah"] >= 130)]
```

---

## D. Teknik Lanjutan untuk Kebutuhan AI/ML
### 1. mengubah Nilai Secara Aman (`.loc[]`)
Ketika ingin mengubah nilai data di bawah kondisi tertentu, pemula sering terjebak menulis kode beruntung `df[kondisi][kolom] = nilai_baru` yang memicu **error** memori. Cara satu-satunya yang aman adalah menggunakan `.loc[]`

```python
# Mengubah kategori pasien menjadi 'Lansia' jika Usia di atas 60 tahun secara aman
df.loc[df['Usia'] > 60, 'Kategori'] = 'Lansia'
```

### 2. Ekspresi Filter SQL Kloning (`.query()`)
Alternatif penulisan filter kondisi rumit agar kode kita lebih rapi dan mudah dibaca (*clean code*)

```python
# Menggantikan penulisan kurung siku yang bertumpuk-tumpuk
df_bersih = df.query("Usia > 30 and Tekanan_Darah >= 130")
```

---

In [11]:
import pandas as pd
import numpy as np

In [12]:
# dataset
data = {
    "Nama": ["Ali", "Budi", "Cici", "Dedi"],
    "Usia": [23, 45, 31, 35],
    "Tekanan_Darah": [120, 140, 118, 130],
}
df_pasien = pd.DataFrame(data, index=["P1", "P2", "P3", "P4"])

In [ ]:
# Barcket Notion -> untuk mengambil kolom atau baris
# []

# 1. Mengambil 1 kolom sebagai Series -> menggunakan 1 bracket []
display(df_pasien["Usia"])

# 2. Mengambil 2 kolom sebagai dataframe -> menggunakan 2 bracket [[]]
display(df_pasien[["Usia", "Tekanan_Darah"]])

P1    23
P2    45
P3    31
P4    35
Name: Usia, dtype: int64

    Usia  Tekanan_Darah
P1    23            120
P2    45            140
P3    31            118
P4    35            130

In [ ]:
# Seleksi berdasarkan label
# .loc[]

# 1. Mengambil P2 untuk semua kolom -> Series
display(df_pasien.loc["P2", :])

# 2. Mengambil P2 sampai P3 hanya untuk kolom 'Nama' dan 'Tekanan_Darah' -> DataFrame
display(df_pasien.loc["P2":"P3", ["Nama", "Tekanan_Darah"]])

Nama             Budi
Usia               45
Tekanan_Darah     140
Name: P2, dtype: object

    Nama  Tekanan_Darah
P2  Budi            140
P3  Cici            118

In [ ]:
# Seleksi berdasarkan index
# .iloc[]

# 1. Mengambil baris terkahir (index -1) untuk semua kolom
display(df_pasien.iloc[-1, :])

# 2. Mengambil baris index 1-3 serta kolom index 0 sampai sebelum 2 (kolom 0 dan 1)
display(df_pasien.iloc[1:3, 0:3])

Nama             Dedi
Usia               35
Tekanan_Darah     130
Name: P4, dtype: object

    Nama  Usia  Tekanan_Darah
P2  Budi    45            140
P3  Cici    31            118

In [ ]:
# Seleksi Berdasarkan Kondisi
# >, >=, <, <=, dan lain-lain

# 1. Mencari usia yang diatas 30 tahun
display(df_pasien["Usia"] > 30)

# 2. Memasukkan kondisi ke Dataframe untuk menampilkan data
display(df_pasien[df_pasien["Usia"] > 30])

# 3. Filter beberapa kondisi menggunakan berbagai operator (and or)
display(df_pasien[(df_pasien["Usia"] > 30) & (df_pasien["Tekanan_Darah"] >= 130)])

P1    False
P2     True
P3     True
P4     True
Name: Usia, dtype: bool

    Nama  Usia  Tekanan_Darah
P2  Budi    45            140
P3  Cici    31            118
P4  Dedi    35            130

    Nama  Usia  Tekanan_Darah
P2  Budi    45            140
P4  Dedi    35            130

In [ ]:
# Mengubah Nilai Secara Aman -> menghindari SettingWithCopyWarning
# .loc[]
df_pasien.loc[df_pasien['Usia'] > 34, 'Kategori'] = 'Risiko Tinggi'
df_pasien

    Nama  Usia  Tekanan_Darah       Kategori
P1   Ali    23            120            NaN
P2  Budi    45            140  Risiko Tinggi
P3  Cici    31            118            NaN
P4  Dedi    35            130  Risiko Tinggi

In [ ]:
# Alternatif Slicing 
# .query()
display(df_pasien.query("Usia > 30 and Tekanan_Darah >= 130"))

    Nama  Usia  Tekanan_Darah       Kategori
P2  Budi    45            140  Risiko Tinggi
P4  Dedi    35            130  Risiko Tinggi