In [1]:
import pandas as pd
import numpy as np

In [8]:
# dataset
data = {
    "Nama": ["Ali", "Budi", "Cici", "Dedi"],
    "Usia": [23, 45, 31, 35],
    "Tekanan_Darah": [120, 140, 118, 130],
}
df_pasien = pd.DataFrame(data, index=["P1", "P2", "P3", "P4"])

In [ ]:
# Barcket Notion -> untuk mengambil kolom atau baris
# 1. Mengambil 1 kolom sebagai Series -> menggunakan 1 bracket []
display(df_pasien["Usia"])

# 2. Mengambil 2 kolom sebagai dataframe -> menggunakan 2 bracket [[]]
display(df_pasien[["Usia", "Tekanan_Darah"]])

P1    23
P2    45
P3    31
P4    35
Name: Usia, dtype: int64

    Usia  Tekanan_Darah
P1    23            120
P2    45            140
P3    31            118
P4    35            130

In [ ]:
# Seleksi berdasarkan label
# 1. Mengambil P2 untuk semua kolom -> Series
display(df_pasien.loc["P2", :])

# 2. Mengambil P2 sampai P3 hanya untuk kolom 'Nama' dan 'Tekanan_Darah' -> DataFrame
display(df_pasien.loc["P2":"P3", ["Nama", "Tekanan_Darah"]])

Nama             Budi
Usia               45
Tekanan_Darah     140
Name: P2, dtype: object

    Nama  Tekanan_Darah
P2  Budi            140
P3  Cici            118

In [16]:
# Seleksi berdasarkan index
# 1. Mengambil baris terkahir (index -1) untuk semua kolom
display(df_pasien.iloc[-1, :])

# 2. Mengambil baris index 1-3 serta kolom index 0 sampai sebelum 2 (kolom 0 dan 1)
display(df_pasien.iloc[1:3, 0:3])

Nama             Dedi
Usia               35
Tekanan_Darah     130
Name: P4, dtype: object

    Nama  Usia  Tekanan_Darah
P2  Budi    45            140
P3  Cici    31            118

In [ ]:
# Seleksi Berdasarkan Kondisi
# 1. Mencari usia yang diatas 30 tahun
display(df_pasien["Usia"] > 30)

# 2. Memasukkan kondisi ke Dataframe untuk menampilkan data
display(df_pasien[df_pasien["Usia"] > 30])

# 3. Filter beberapa kondisi menggunakan berbagai operator (and or)
display(df_pasien[(df_pasien["Usia"] > 30) & (df_pasien["Tekanan_Darah"] >= 130)])

P1    False
P2     True
P3     True
P4     True
Name: Usia, dtype: bool

    Nama  Usia  Tekanan_Darah
P2  Budi    45            140
P3  Cici    31            118
P4  Dedi    35            130

    Nama  Usia  Tekanan_Darah
P2  Budi    45            140
P4  Dedi    35            130